### PR TITLE
Noammir/feat/add task manager

### PR DESCRIPTION
**Pull request by noammirjani**
Create a basic TaskManager and Task Classes for managing Tasks.

- There are two main classes that were added, Task and TaskManager. Both have a fit test file.
-  there is an exceptions file with all the inherents exceptions I had creates and used in those classes.

### CODE REVIEW

**Comment by daviddsapir** [comment]
Looks great!

Please review the PR and change any single-line formats to multi-line where appropriate.

Additionally, I believe we should assign task IDs based on the session rather than using them as classifiers. The session-based task IDs will correspond to the order of tasks when loading them from the JSON. The actual unique ID (UID) will be a hash generated by us, similar to the way Git creates hashes, ensuring there are no collisions.

For Example:

ID | UID
-- | --
1 | 92026fb0
2 | d253a6ad

**Comment by noammirjani** [comment]
> Looks great!
> 
> Please review the PR and change any single-line formats to multi-line where appropriate.
> 
> Additionally, I believe we should assign task IDs based on the session rather than using them as classifiers. The session-based task IDs will correspond to the order of tasks when loading them from the JSON. The actual unique ID (UID) will be a hash generated by us, similar to the way Git creates hashes, ensuring there are no collisions.
> 
> For Example:
> 
> ID	UID
> 1	92026fb0
> 2	d253a6ad
> The ID/UID will be used by the user solely for referencing other tasks. The IDs/UIDs are primarily for our internal use, basically management with both local and remote (Google API, Outlook cal, etc.).

does the id, uid is a change that is required now, or change to do in the future?

**Comment by daviddsapir** [comment]
Please have a look at the **most** popular coding style of python - [black](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html).

You can add it as an extension to refactor your code while working.

**Comment by daviddsapir** [comment]
About the ID & UID, this is an issue that better be solved now.

The fix is straight forward.

**Review by daviddsapir — APPROVED** [review]

**Pull request merged**
